config/routes.rb
Ploutos::Application.routes.draw do
  get "overviews/index"
  resources :fixed_costs
  resources :types
  resources :incomes
  resources :sudden_checks

  patch "update_data"   => "users#update_data"
  patch "edit_password"    => "users#update_password"

  get "edit_data" => "users#edit_data"

  get "sign_in"       => "users#sign_in"
  get "sign_up"       => "users#sign_up"
  get "log_in"        => "users#log_in"
  post "new_user"     => "users#create"
  post "activate"     => "users#activate"  
  get "deactivate"    => "users#deactivate"
  get "edit_password" => "users#edit_password"

  get "due_payments"  => "bills#index"
  patch "due_payments/:id" => "bills#pay", as: :bill

  root 'overviews#index' 

  

end

app/controllers/overviews_controller.rb
class OverviewsController < ApplicationController
before_action :authenticate, only: [:index]
  include Finance

  def index
    @status = Status.new @current_user
  end
end

app/helpers/overviews_helper.rb
module OverviewsHelper
end

app/views/overviews/_messages.html.erb
<% if @message %>


<% if @message[:success] %>
  <div class="alert alert-success">
    <a class="close" data-dismiss="alert">x</a>
    <%= @message[:success] %>
  </div>
<% end %>

<% if @message[:error] %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">x</a>
    <% @message[:error].each do |error| %>
      <%= error %><br />
    <% end %>
  </div>
<% end %>

<% if @message[:info] %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert">x</a>
    <%= @message[:info] %>
  </div>
<% end %>


<% else %>

<% if flash[:success] %>
  <div class="alert alert-success">
    <a class="close" data-dismiss="alert">x</a>
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">x</a>
    <% flash[:error].each do |error| %>
      <%= error %><br />
    <% end %>
  </div>
<% end %>

<% if flash[:info] %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert">x</a>
    <%= flash[:info] %>
  </div>
<% end %>


<% end %>

app/views/overviews/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
</ul>
<ul class="nav">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Overview<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Incomes', incomes_path %></li>
      <li><%= link_to 'Fixed costs', fixed_costs_path %></li>
      <li><%= link_to 'Unexpected checks', sudden_checks_path %></li>
    </ul>
  </li>
</ul>
<ul class="nav">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Add<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'New income', new_income_path %></li>
      <li><%= link_to 'New fixed cost', new_fixed_cost_path %></li>
      <li><%= link_to 'Unexpected income', new_sudden_check_path(:is_income => 1) %></li>
      <li><%= link_to 'Unexpected cost', new_sudden_check_path(:is_income => -1) %></li>
    </ul>
  </li>
</ul>
<ul class="nav">
  <li><%= link_to 'Due payments', due_payments_path %></li>
</ul>
<ul class="nav">
  <% if @current_user %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">User<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Change password', edit_password_path %></li>
        <li><%= link_to 'Change data', edit_data_path %></li>
        <li><%= link_to 'Log out', deactivate_path %></li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to 'Sign up', sign_up_path %></li>
  <% end %>
</ul>

app/views/overviews/index.html.erb
<h1>Your finances</h1>

<p>Spendable: <%= @status.spendable %></p>
<p>Income: <%= @status.income %></p>
<p>Bills: <%= @status.cost %></p>
<p>Savings: <%= @status.savings %>%</p>
<p>Unexpected income: <%= @status.sudden_income %></p>