config/routes.rb
Ploutos::Application.routes.draw do
  get "overviews/index"
  resources :fixed_costs
  resources :types
  resources :incomes
  resources :sudden_checks

  patch "update_data"   => "users#update_data"
  patch "edit_password"    => "users#update_password"

  get "edit_data" => "users#edit_data"

  get "sign_in"       => "users#sign_in"
  get "sign_up"       => "users#sign_up"
  get "log_in"        => "users#log_in"
  post "new_user"     => "users#create"
  post "activate"     => "users#activate"  
  get "deactivate"    => "users#deactivate"
  get "edit_password" => "users#edit_password"

  get "due_payments"  => "bills#index"
  patch "due_payments/:id" => "bills#pay", as: :bill

  root 'overviews#index' 

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true

  validates :password, length: { minimum: 6 }, :on => :create
  validates :password, length: { minimum: 6 }, :on => :update_password
  
  validate :password_equal_to_confirmation, :on => :create
  validate :password_equal_to_confirmation, :on => :update_password


  validates :savings, numericality: { greater_than_or_equal_to: 0 }

  validates :username, :uniqueness => true

  has_many :fixed_costs, dependent: :destroy
  has_many :incomes, dependent: :destroy
  has_many :sudden_checks, dependent: :destroy
  has_many :types, dependent: :destroy

  def password_equal_to_confirmation
    if self.password != self.password_confirmation
      errors.add(:password, 'must equal the confirmation')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate, only: [:update_data, :edit_data, :update_password, :edit_password]
  def create
    @user = User.new user_params
    @user.savings = BigDecimal.new '0'    

    if @user.save
      notify :success, 'User created successfully.', true

      redirect_to log_in_path
    else
      notify :error, @user.errors.full_messages

      render 'sign_up'
    end
  end

  def sign_up
    @user = User.new
  end

  #direct to login page
  def log_in
  end

  # Actual log-in
  def activate
    credentials = params[:user].permit(:username, :password)
    @user = User.find_by username: credentials[:username]

    if( @user && @user.authenticate(credentials[:password]) )
      reset_session

      notify :info, 'Welcome.', true

      session[:user_id] = @user.id 
      redirect_to overviews_index_path
    else
      notify :error, ['Username and/or Password is incorrect'], true

      redirect_to log_in_path
    end
  end

  # Log-out
  def deactivate
    session[:user_id] = nil

    notify :info, 'You are logged out.', true

    redirect_to log_in_path
  end

  def edit_password
  end

  def update_password
    credentials = params[:user].permit(:password, :password_confirmation)
    old_password = params[:user].permit(:old_password)[:old_password]

    if !@current_user.authenticate( old_password )
      notify :error, ['Incorrect password']

      render 'edit_password'
      return
    end

    @current_user.password = credentials[:password]
    @current_user.password_confirmation = credentials[:password_confirmation]

    if @current_user.valid? :update_password
      @current_user.update credentials

      notify :success, 'Password updated successfully', true

      redirect_to root_path
    else
      notify :error, @current_user.errors.full_messages

      render 'edit_password'
    end
  end

  def edit_data
  end

  def update_data 
    if @current_user.update params[:user].permit(:savings)
      notify :success, 'Successfully changed your data', true

      redirect_to root_path
    else
      notify :error, @current_user.errors.full_messages

      render 'edit_data'
    end
  end

  def user_params
    params[:user].permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_data.html.erb
<%= form_for @current_user, url: update_data_path do |f| %>
  <p>
    <%= f.label :savings %>
    <%= f.text_field :savings %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/users/access_violation.html.erb
<p>Access Violation</p>

app/views/users/edit_data.html.erb
<%= render 'users/form_data' %>

app/views/users/edit_password.html.erb
<%= form_for @current_user, url: edit_password_path do |f| %>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :old_password %>
    <%= f.password_field :old_password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/log_in.html.erb
<div class="span1">
<table class="table table-bordered">
<%= form_for :user, url: activate_path do |f| %>
  <tr>
    <td><%= f.label :username, :style => "display:inline" %></td>
    <td><%= f.text_field :username %></td>
  </tr>
  <tr>
    <td><%= f.label :password, :style => "display:inline" %></td>
    <td><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td><%= f.submit 'Log in' %></td>
    <td></td>
  </tr>
<% end %>
</table>
</div>

app/views/users/sign_up.html.erb
<%= form_for @user, url: new_user_path do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit %></p>
<% end %>