config/routes.rb
Ploutos::Application.routes.draw do
  get "overviews/index"
  resources :fixed_costs
  resources :types
  resources :incomes
  resources :sudden_checks

  patch "update_data"   => "users#update_data"
  patch "edit_password"    => "users#update_password"

  get "edit_data" => "users#edit_data"

  get "sign_in"       => "users#sign_in"
  get "sign_up"       => "users#sign_up"
  get "log_in"        => "users#log_in"
  post "new_user"     => "users#create"
  post "activate"     => "users#activate"  
  get "deactivate"    => "users#deactivate"
  get "edit_password" => "users#edit_password"

  get "due_payments"  => "bills#index"
  patch "due_payments/:id" => "bills#pay", as: :bill

  root 'overviews#index' 

  

end

app/models/sudden_check.rb
class SuddenCheck < ActiveRecord::Base
  belongs_to :user

  validates :is_income, presence: true
  validate  :is_income_valid?

  validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def is_income_valid?
    unless self.is_income != nil && self.is_income.abs == 1
      errors.add(:is_income, 'is not equal to 1 or -1')
    end
  end
end

app/controllers/sudden_checks_controller.rb
class SuddenChecksController < ApplicationController
before_action :authenticate
  def new
    @sudden_check = @current_user.sudden_checks.build
    @sudden_check.is_income = params[:is_income]
  end

  def edit
    return unless allow_view? params[:id]
  end

  def index
    @sudden_checks = @current_user.sudden_checks.order when: :desc
  end

  def show
    return unless allow_view? params[:id]
  end

  def create
    @sudden_check = @current_user.sudden_checks.build sudden_check_params

    if @sudden_check.save
      notify :success, 'Unexpected check added successfully.', true

      redirect_to sudden_checks_path
    else
      notify :error, @sudden_check.errors.full_messages

      render 'new'
    end
  end

  def update
    return unless allow_view? params[:id]

    if @sudden_check.update sudden_check_params
      notify :success, 'Unexpected check updated successfully.', true

      redirect_to sudden_checks_path
    else
      notify :error, @sudden_check.errors.full_messages

      render 'edit'
    end
  end

  def destroy
    return unless allow_view? params[:id]

    notify :info, 'Sudden check deleted.', true

    @sudden_check.destroy
    redirect_to sudden_checks_path
  end

  def sudden_check_params
    params[:sudden_check].permit(:when, :amount, :is_income, :description)
  end

  def allow_view? id
    @sudden_check = SuddenCheck.find id

    if @sudden_check.user_id != @current_user.id
      render 'users/access_violation' and return false
    end
    return true
  end
end

app/helpers/sudden_checks_helper.rb
module SuddenChecksHelper
end

app/views/sudden_checks/_form.html.erb
<%= form_for @sudden_check, url: sudden_check_path(@sudden_check) do |f| %>
  <p>
    <%= f.label :when %>
    <%= f.date_select :when %>
  </p>
  <p>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.hidden_field :is_income %>
    <%= f.submit 'Create check' %>
  </p>
<% end %>

app/views/sudden_checks/_table.html.erb
<tr>
  <td><%= sudden_check.amount * sudden_check.is_income %></td>
  <td><%= sudden_check.when %></td>
  <td><%= link_to 'Details', sudden_check_path(sudden_check) %></td>
  <td><%= link_to 'Edit', edit_sudden_check_path(sudden_check) %></td>
  <td><%= link_to 'Delete', sudden_check_path(sudden_check), method: :delete %></td>
</tr>

app/views/sudden_checks/edit.html.erb
<%= render 'form' %>

app/views/sudden_checks/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sudden_checks.each do |sudden_check| %>
      <%= render 'table', :sudden_check => sudden_check %>
    <% end %>
  </tbody>
</table>

app/views/sudden_checks/new.html.erb
<%= render 'form' %>

app/views/sudden_checks/show.html.erb
<p>
  Date: <%= @sudden_check.when %>
</p>
<p>
  Amount: <%= @sudden_check.amount * @sudden_check.is_income %>
</p>
<p>
  Description: <%= @sudden_check.description %>
</p>
  