config/routes.rb
Ploutos::Application.routes.draw do
  get "overviews/index"
  resources :fixed_costs
  resources :types
  resources :incomes
  resources :sudden_checks

  patch "update_data"   => "users#update_data"
  patch "edit_password"    => "users#update_password"

  get "edit_data" => "users#edit_data"

  get "sign_in"       => "users#sign_in"
  get "sign_up"       => "users#sign_up"
  get "log_in"        => "users#log_in"
  post "new_user"     => "users#create"
  post "activate"     => "users#activate"  
  get "deactivate"    => "users#deactivate"
  get "edit_password" => "users#edit_password"

  get "due_payments"  => "bills#index"
  patch "due_payments/:id" => "bills#pay", as: :bill

  root 'overviews#index' 

  

end

app/models/fixed_cost.rb
class FixedCost < ActiveRecord::Base
  attr_accessor :priority

  belongs_to :type

  validates :amount, :type_id, :frequency, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  validates :type_id, numericality: { only_integer: true }

  validates :frequency, numericality: { greater_than: 0 }
  validates :priority, numericality: { greater_than_or_equal_to: 0, only_integer: true }, :on => :create

  has_many :bills, dependent: :destroy

  # Iterate over all unpaid bills
  def each_unpaid
    self.bills.each do |bill|
      unless bill.payed?
        yield bill
      end
    end
  end
end

app/models/fixed_costs.rb
class FixedCosts < ActiveRecord::Base
  def amount
    return BigDecimal.new(amountRound().to_s) + BigDecimal.new(amountDecimal.to_s) / 100
  end

  belongs_to :type

  validates :amountRound, numericality: { only_integer: true }
  validates :amountDecimal, :inclusion => 1...100

  validates :type_id, numericality: { only_integer: true }
  validates :frequency, numericality: { only_integer: true }
end

app/controllers/fixed_costs_controller.rb
class FixedCostsController < ApplicationController
before_action :authenticate
before_action :sort_priority, only: [:index, :create, :update, :destroy]

include CustomContainer
  def sort_priority
    @fixed_costs = @current_user.fixed_costs
    @priority = LinkedList.new @fixed_costs
  end

  def new
    @fixed_cost = @current_user.fixed_costs.build
    @types = @current_user.types
  end
  
  def edit
    return unless allow_view? params[:id]

    @types = @current_user.types
  end

  def index
    @fixed_costs = @current_user.fixed_costs
  end

  def show
    return unless allow_view? params[:id]
  end

  def create
    @fixed_cost = @fixed_costs.build fixed_cost_params

    if @fixed_cost.save
      @priority.insert @fixed_cost, @fixed_cost.priority.to_i - 1

#      @priority.each_affected { |fixed_cost| fixed_cost.update fixed_cost.changed }

      notify :success, 'Fixed Cost added successfully.', true

      redirect_to fixed_costs_path
    else
      notify :error, @fixed_cost.errors.full_messages

      @types = @current_user.types
      render 'new'
    end
  end

  def update
    return unless allow_view? params[:id]
    parameters = fixed_cost_params
    if @fixed_cost.update parameters

      if parameters[:priority] != nil
        @priority.move @fixed_cost, parameters[:priority].to_i - 1
      end

      notify :success, 'Fixed Cost updated successfully.', true

      redirect_to fixed_costs_path
    else
      notify :error, @fixed_cost.errors.full_messages

      @types = @current_user.types
      render 'edit'
    end
  end

  def destroy
    return unless allow_view? params[:id]

    notify :info, 'Fixed Cost deleted.', true
    
    @priority.delete @fixed_cost
#    @priority.each_affected { |fixed_cost| fixed_cost.update fixed_cost.changed }

    @fixed_cost.destroy
    redirect_to fixed_costs_path
  end

  def fixed_cost_params
    parameters = params[:fixed_cost].permit(:type_id, :first_payment, :amount, :frequency, :priority, :description)
    if parameters[:priority] == nil
      parameters[:next] = nil
      parameters[:prev] = nil
    end

    return parameters
  end

  def allow_view? id
    @fixed_cost = FixedCost.find id

    if @fixed_cost.user_id != @current_user.id
      render 'users/access_violation' and return false
    end
    return true
  end
end

app/helpers/fixed_costs_helper.rb
module FixedCostsHelper
end

app/views/fixed_costs/_form.html.erb
<%= form_for @fixed_cost, url: fixed_cost_path(@fixed_cost) do |f| %> 
  <p>
    <%= f.label :type_id %>
    <%= f.select :type_id, @types.map { |type| [type.name,type.id] }, {}, :onchange => 'set_link()' %>
    <%= link_to 'Add type', new_type_path %>
    <%= link_to 'Edit type', edit_type_path(@types[0]), :id => 'edit_type' %>
    <%= link_to 'Destroy', type_path(@types[0]), method: :delete, :id => 'destroy_type' %>
  </p>
  <p>
    <%= f.label :first_payment %>
    <%= f.date_select :first_payment, { :discard_day => true } %>
  </p>
  <p>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :frequency %>
    <%= f.text_field :frequency %>
  </p>
  <p>
    <%= f.label :priority %>
    <%= f.text_field :priority %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/fixed_costs/_table.html.erb
<tr>
  <td><%= fixed_cost.amount %></td>
  <td><%= fixed_cost.frequency %></td>
  <td><%= fixed_cost.type.name %></td>
  <td><%= link_to 'Details', fixed_cost_path(fixed_cost) %></td>
  <td><%= link_to 'Edit', edit_fixed_cost_path(fixed_cost) %></td>
  <td><%= link_to 'Delete', fixed_cost_path(fixed_cost), method: :delete %></td>
</tr>

app/views/fixed_costs/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Cost per Payment</th>
      <th>X monthly payment</th>
      <th>Type of Payment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @priority.each do |fixed_cost| %>
      <%= render 'table', :fixed_cost => fixed_cost %>
    <% end %>
  </tbody>
</table>

app/views/fixed_costs/new.html.erb
<% if @fixed_cost.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@fixed_cost.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @fixed_cost.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @fixed_cost, url: fixed_costs_path do |f| %> 
  <p>
    <%= f.label :type_id %>
    <%= f.select :type_id, @types.map { |type| [type.name,type.id] } %>
  </p>
  <p>
    <%= f.label "Cost per month." %>
    <%= f.text_field :amountRound %>, 
      <%= f.text_field :amountDecimal %>
  </p>
  <p>
    <%= f.label :frequency %>
    <%= f.text_field :frequency %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/fixed_costs/show.html.erb
<p>
  Type: <%= @fixed_cost.type.name %>.
</p>
<p>
  Cost per Payment: <%= @fixed_cost.amount %>.
<p>
  <%= @fixed_cost.frequency %> Monthly payment.
</p>
<p>
  Description: <%= @fixed_cost.description %>
</p>